name: Release

on:
  workflow_dispatch:

jobs:
  loadversion:
    runs-on: windows-latest
    outputs:
      version: ${{ steps.loadversion.outputs.version }}
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: build.py
          sparse-checkout-cone-mode: false
      - id: loadversion
        run: python build.py loadversion | Out-File -FilePath $Env:GITHUB_OUTPUT -Encoding utf8 -Append
  build_xp:
    runs-on: windows-2019
    needs: loadversion
    strategy:
      matrix:
        language: [Chinese,English,Russian,TradChinese]
    permissions:
      id-token: write
      attestations: write
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: GuillaumeFalourd/setup-windows10-sdk-action@v2
        with:
          sdk-version: 22621
      - run: python build.py build ${{ matrix.language }} winxp

      - run: python scripts/pack.py

      # - name: Generate attestation for artifact
      #   uses: actions/attest-build-provenance@v1
      #   with:
      #     subject-path: builds/${{ matrix.target }}.zip
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.language }}_winxp
          path: builds/Release_${{ matrix.language }}_winxp.zip
      - uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ needs.loadversion.outputs.version }}
          files: builds/Release_${{ matrix.language }}_winxp.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
  build_plugin:
    runs-on: windows-latest
    needs: [loadversion]
    strategy:
      matrix:
        include:
          - cmd: plg32
            qtarch: win32_msvc2019
            target: plugin32
          - cmd: plg64
            qtarch: win64_msvc2019_64
            target: plugin64
    permissions:
      id-token: write
      attestations: write
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: GuillaumeFalourd/setup-windows10-sdk-action@v2
        with:
          sdk-version: 22621
      
      - uses: jurplel/install-qt-action@v3.3.0
        with:
          version:      5.15.2
          host:         windows
          target:       desktop
          arch:         ${{ matrix.qtarch }}
          dir:          ${{ runner.temp }}
          setup-python: true
      - run: python build.py ${{ matrix.cmd }}

      - run: python scripts/pack.py

      # - name: Generate attestation for artifact
      #   uses: actions/attest-build-provenance@v1
      #   with:
      #     subject-path: builds/${{ matrix.target }}.zip
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.target }}
          path: builds/${{ matrix.target }}.zip
      - uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ needs.loadversion.outputs.version }}
          files: builds/${{ matrix.target }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        language: [Chinese,English,Russian,TradChinese]
        bits: [32, 64]
    permissions:
      id-token: write
      attestations: write
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: GuillaumeFalourd/setup-windows10-sdk-action@v2
        with:
          sdk-version: 22621
      - run: python build.py build ${{ matrix.language }} ${{matrix.bits}}

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.language }}_${{matrix.bits}}
          path: builds
  
  release:
    runs-on: windows-latest
    needs: [build, loadversion]
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: build.py
          sparse-checkout-cone-mode: false
      - uses: actions/download-artifact@v4
        with:
            path: build
      - run: python build.py merge
      - uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ needs.loadversion.outputs.version }}
          files: builds/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}